# This is a basic workflow to help you get started with Actions1111

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install flake8 isort black pytest aiohttp bs4 requests
          ls -la
          flake8 --ignore=E203 /__w/homework-repository/homework-repository/homework2/task5.py /__w/homework-repository/homework-repository/homework7/task2.py
          isort --check .
          black --line-length 80 --check .
          py.test tests
